server {
    listen 80;
    server_name localhost;

    client_max_body_size 1024M;
    
    root /var/www/html;
    index index.php index.html;

    # Variável de controle de cache
    set $skip_cache 0;

    # POST
    if ($request_method = POST) {
        set $skip_cache 1;
    }

    # Query string
    if ($query_string != "") {
        set $skip_cache 1;
    }

    # Admin e login
    if ($request_uri ~* "/wp-admin|/wp-login.php") {
        set $skip_cache 1;
    }

    # WooCommerce URLs
    if ($request_uri ~* "/cart|/checkout|/my-account|/wc-api|/add-to-cart") {
        set $skip_cache 1;
    }

    # Cookies
    if ($http_cookie ~* "wordpress_logged_in|woocommerce_items_in_cart|woocommerce_cart_hash|wp_woocommerce_session") {
        set $skip_cache 1;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_read_timeout 1200s;
        fastcgi_send_timeout 1200s;
        fastcgi_connect_timeout 1200s;

        fastcgi_cache WORDPRESS;
        fastcgi_cache_valid 200 301 302 60m;
        fastcgi_cache_bypass $skip_cache;
        fastcgi_no_cache $skip_cache;

        fastcgi_cache_use_stale error timeout invalid_header updating http_500 http_503;

        add_header X-FastCGI-Cache $upstream_cache_status always;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        access_log off;
    }
}
