# =====================================
# Virtual Host WordPress (OpenLiteSpeed)
# =====================================

docRoot                   /var/www/html
vhDomain                  localhost
vhAliases                 *

enableGzip                1

# =====================================
# Index
# =====================================
index {
  useServer               0
  indexFiles              index.php index.html
}

# =====================================
# Rewrite (WordPress depende disso)
# =====================================
rewrite {
  enable                  1
  autoLoadHtaccess        1
}

# =====================================
# CONTEXTO PHP (GLOBAL)
# =====================================
context ~ \.php$ {
  type                    lsapi
  location                $DOC_ROOT/
  allowBrowse             0
  addHandler              lsapi:lsphp
}

# =====================================
# LSAPI PHP
# =====================================
extProcessor lsphp {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp.sock
  maxConns                20
  initTimeout             60
  retryTimeout            0
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp85/bin/lsphp
}
