version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:3.72.0
    container_name: imd-nexus
    restart: always
    user: "200:200"
    expose:
      - "8081" # Web UI / Maven / NPM (Acessível via rede Docker para o Ingress)
      - "8082" # Docker Registry / Proxy (Acessível via rede Docker para o Ingress)
    ports:
      - "9001:8081" # Mantido apenas se quiser acessar o Nexus diretamente via localhost:9001 (opcional/debug)
    volumes:
      - ./nexus_data:/nexus-data
    networks:
      - ingress-network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"

networks:
  ingress-network:
    external: true