version: "3.9"
services:
  nexus:
    image: sonatype/nexus3:3.72.0
    command: ['sh', '-c', 'chown -R 200:200 /nexus-data && $${SONATYPE_DIR}/start-nexus-repository-manager.sh']
    container_name: imd-nexus
    ports:
      - 9001:8081
      - 9002:8082
    volumes:
      - nexus-data:/nexus-data
    networks:
      - nexus-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
volumes:
    nexus-data:
        external: true
        name: nexus-data
networks:
  nexus-network:
