server {
    listen 80;
    server_name sonar.stmcurso.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sonar.stmcurso.com.br;

    ssl_certificate /etc/nginx/ssl/stm_curso.crt;
    ssl_certificate_key /etc/nginx/ssl/stm_curso_private_key.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # proxy_pass http://sonarqube_container:9000;
        default_type text/html;
        return 200 '<h1>Bem-vindo ao SonarQube (HTTPS)</h1>';
    }
}
